window.ALFA_PUBLIC_PILOT = Object.freeze({
  schemaVersion: "alfa_public_bilingual_annotation_package_v2",
  packageId: "PUBLIC-CALIBRATION-TR-EN-150-V1",
  status: "UNLABELED_DEVELOPMENT_CALIBRATION_BANK",
  expectedLabelsIncluded: false,
  blockSize: 50,
  blocks: Object.freeze([
    Object.freeze({ id: "BLOCK-01", order: 1, itemCount: 50 }),
    Object.freeze({ id: "BLOCK-02", order: 2, itemCount: 50 }),
    Object.freeze({ id: "BLOCK-03", order: 3, itemCount: 50 })
  ]),
  items: Object.freeze([
    { id: "PUB-001", blockId: "BLOCK-01", tr: "Ekip erişim denetimini her ay yeniden değerlendirir.", en: "The team reviews access controls every month." },
    { id: "PUB-002", blockId: "BLOCK-01", tr: "Rapor hem tamamlandığını hem de hiç başlamadığını söylüyor.", en: "The report says that it was both completed and never started." },
    { id: "PUB-003", blockId: "BLOCK-01", tr: "### notlar dağınık ama sonuç açık: güvenlik açığı kapatılmadan yayın yapılmayacak.", en: "### the notes are scattered, but the conclusion is clear: publication will wait until the security flaw is fixed." },
    { id: "PUB-004", blockId: "BLOCK-01", tr: "Mavi çatal sessizliği yedi ve takvimi üçgenle ölçtü.", en: "The blue fork ate the silence and measured the calendar with a triangle." },
    { id: "PUB-005", blockId: "BLOCK-01", tr: "vrak tum zeli @@ 17 qop nera", en: "vrak tum zeli @@ 17 qop nera" },
    { id: "PUB-006", blockId: "BLOCK-01", tr: "Kısa vadede hız önemlidir; uzun vadede doğruluk daha önemlidir. İki hedef birlikte yönetilebilir.", en: "Speed matters in the short term; accuracy matters more in the long term. Both goals can be managed together." },
    { id: "PUB-007", blockId: "BLOCK-01", tr: "Servis gece boyunca kesintisiz çalıştı. Aynı rapor servisin 02.15'te tamamen durduğunu belirtiyor.", en: "The service ran without interruption all night. The same report states that it stopped completely at 02:15." },
    { id: "PUB-008", blockId: "BLOCK-01", tr: "kullnıcı izinlrini gncelledi, kayıt biraz bozuk; yine de erişim kararı anlaşılabiliyor.", en: "the usr updatd permissions, and the record is somewhat corrupted; the access decision is still understandable." },
    { id: "PUB-009", blockId: "BLOCK-01", tr: "Bazen hızlı karar gerekir, bazen ayrıntılı inceleme gerekir; seçim koşullara göre yapılır.", en: "Sometimes a fast decision is needed, and sometimes a detailed review is needed; the choice depends on the conditions." },
    { id: "PUB-010", blockId: "BLOCK-01", tr: "Adalet herkese eşit uygulanır; aynı madde yöneticilere farklı hukuk tanır.", en: "Justice applies equally to everyone; the same article grants managers a different legal standard." },
    { id: "PUB-011", blockId: "BLOCK-01", tr: "Yeni sürüm cuma günü yayımlanacak çünkü güvenlik testleri perşembe günü tamamlanıyor.", en: "The new version will be released on Friday because the security tests finish on Thursday." },
    { id: "PUB-012", blockId: "BLOCK-01", tr: "Bulut merdiveni düşünceyi kaynattı, sonra dünün rengini dinledi.", en: "The cloud ladder boiled the thought and then listened to the color of yesterday." },
    { id: "PUB-013", blockId: "BLOCK-01", tr: "@@ x9 klem pru zz 44 ??", en: "@@ x9 klem pru zz 44 ??" },
    { id: "PUB-014", blockId: "BLOCK-01", tr: "Model hatasız sonuç garanti ediyor fakat kararlarını rastgele seçtiğini açıklıyor.", en: "The model guarantees error-free results but explains that it selects its decisions randomly." },
    { id: "PUB-015", blockId: "BLOCK-01", tr: "Toplantı notları uzun ve tekrarlııı; ana karar bütçenin yeniden incelenmesi.", en: "The meeting notes are long and repetitivvve; the main decision is to review the budget again." },
    { id: "PUB-016", blockId: "BLOCK-01", tr: "Bir yöntem hızlıdır, diğeri daha ayrıntılı sonuç verir. Seçim ihtiyaca göre yapılır.", en: "One method is fast, while the other provides more detailed results. The choice depends on the need." },
    { id: "PUB-017", blockId: "BLOCK-01", tr: "Kurum hiçbir veriyi saklamadığını ve aynı veriyi süresiz arşivlediğini bildiriyor.", en: "The institution states that it stores no data and archives the same data indefinitely." },
    { id: "PUB-018", blockId: "BLOCK-01", tr: "Protokol, her değişikliğin iki bağımsız kişi tarafından doğrulanmasını gerektirir.", en: "The protocol requires every change to be verified by two independent people." },
    { id: "PUB-019", blockId: "BLOCK-01", tr: "Işık, kararın kokusunu katlayarak boşluğa anlattı.", en: "The light folded the smell of the decision and explained it to the void." },
    { id: "PUB-020", blockId: "BLOCK-01", tr: "zorf mina plok -- uu 8 8 kala", en: "zorf mina plok -- uu 8 8 kala" },
    { id: "PUB-021", blockId: "BLOCK-01", tr: "[taslak] tarih yannlış olabilir ama KARAR: yedekleme tamamlanmadan sunucu kapatılmayacak!!!", en: "[draft] the date may be wrng, but DECISION: the server will not be shut down before the backup is complete!!!" },
    { id: "PUB-022", blockId: "BLOCK-01", tr: "lom perka 33 -- züf narinex qqq", en: "lom perka 33 -- zuf narinex qqq" },
    { id: "PUB-023", blockId: "BLOCK-01", tr: "Sessiz dosya, salı gününü cebine koyarak sıcak bir hesaplama yaptı.", en: "The silent file put Tuesday in its pocket and performed a warm calculation." },
    { id: "PUB-024", blockId: "BLOCK-01", tr: "Kapı yalnız yetkili kartlarla açılır; güvenlik kaydı aynı kapının herhangi bir kart olmadan herkese açıldığını doğruluyor.", en: "The door opens only with authorized cards; the security record confirms that the same door opens to everyone without any card." },
    { id: "PUB-025", blockId: "BLOCK-01", tr: "acilll not // ödeme bugün yapılmalı... eski mesajları boşver, son onay mali işlerden geldi.", en: "urgnt note // payment must be made today... ignore the old messages, final approval came from finance." },
    { id: "PUB-026", blockId: "BLOCK-01", tr: "Pencere, sorumluluğun ağırlığını dakikalarla boyayıp rapora fısıldadı.", en: "The window painted the weight of responsibility with minutes and whispered it to the report." },
    { id: "PUB-027", blockId: "BLOCK-01", tr: "qer 88 vulta :: nem pox ili ili", en: "qer 88 vulta :: nem pox ili ili" },
    { id: "PUB-028", blockId: "BLOCK-01", tr: "Deneyde yalnız A grubu kullanıldı. Yöntem bölümü aynı deneyde A grubunun hiç bulunmadığını söylüyor.", en: "Only group A was used in the experiment. The methods section says that group A was not present in the same experiment." },
    { id: "PUB-029", blockId: "BLOCK-01", tr: "KAYIT-7: sensör bozk / değer eksik / ama uyarı net -> bölge boşaltılsın.", en: "LOG-7: sensor brokn / value missing / but warning clear -> evacuate the area." },
    { id: "PUB-030", blockId: "BLOCK-01", tr: "Yuvarlak gerekçe, kararın gölgesini tartıp öğleden sonrayı kilitledi.", en: "The round justification weighed the decision's shadow and locked the afternoon." },
    { id: "PUB-031", blockId: "BLOCK-01", tr: "nif toru %%% 4b sela mok?", en: "nif toru %%% 4b sela mok?" },
    { id: "PUB-032", blockId: "BLOCK-01", tr: "Sözleşme 1 Haziran'da sona erdi; aynı sözleşmenin 1 Haziran'dan sonra hâlâ yürürlüğe girmediği değil, kesintisiz yürürlükte olduğu yazıyor.", en: "The contract ended on June 1; the same contract is described as remaining continuously in force after June 1." },
    { id: "PUB-033", blockId: "BLOCK-01", tr: "sonuç sonuç sonuç: testler iyi, yalnız üçüncü modül tekrar bakılcak. ref=??", en: "result result result: tests are good, only the third module needs another look. ref=??" },
    { id: "PUB-034", blockId: "BLOCK-01", tr: "Takvim, metal bir düşünceyi suladı ve toplantının sıcaklığını imzaladı.", en: "The calendar watered a metallic thought and signed the temperature of the meeting." },
    { id: "PUB-035", blockId: "BLOCK-01", tr: "prax ulum 0x0 vey nasti kr kr", en: "prax ulum 0x0 vey nasti kr kr" },
    { id: "PUB-036", blockId: "BLOCK-01", tr: "İnceleme tamamlanana kadar belge taslak statüsünde kalacaktır.", en: "The document will remain in draft status until the review is complete." },
    { id: "PUB-037", blockId: "BLOCK-01", tr: "mail zinciri çok uzun >>> fakat tek istek var: teslim tarihini pazartesiye alalım pls.", en: "the email chain is very long >>> but there is one request: move the deadline to Monday pls." },
    { id: "PUB-038", blockId: "BLOCK-01", tr: "Cihaz ölçüm sırasında kapalıydı; sonuç bölümü aynı anda cihazın sürekli veri kaydettiğini bildiriyor.", en: "The device was off during measurement; the results section reports that it continuously recorded data at the same time." },
    { id: "PUB-039", blockId: "BLOCK-01", tr: "Mor kural, boşluğun sesini hesaplayıp kuzeyin sabrını yazdırdı.", en: "The purple rule calculated the sound of emptiness and printed the patience of north." },
    { id: "PUB-040", blockId: "BLOCK-01", tr: "velos nura // 19 jep tali zzzz", en: "velos nura // 19 jep tali zzzz" },
    { id: "PUB-041", blockId: "BLOCK-01", tr: "NOT NOT: yantlar gecikti ama karar değişmedi — toplantı çevrimiçi yapılacak.", en: "NOTE NOTE: respones were late, but the decision did not change — the meeting will be online." },
    { id: "PUB-042", blockId: "BLOCK-01", tr: "Politika uzaktan erişimi tamamen yasaklıyor; sonraki cümle aynı politika kapsamında tüm çalışanlara sınırsız uzaktan erişim veriyor.", en: "The policy completely prohibits remote access; the next sentence grants every employee unlimited remote access under the same policy." },
    { id: "PUB-043", blockId: "BLOCK-01", tr: "Raporun kokusu, iki basamaklı bir sessizliği güneşle çarptı.", en: "The smell of the report multiplied a two-digit silence by the sun." },
    { id: "PUB-044", blockId: "BLOCK-01", tr: "trem ukla 9? siv ronex bibi", en: "trem ukla 9? siv ronex bibi" },
    { id: "PUB-045", blockId: "BLOCK-01", tr: "Yeni kural yalnız gelecek ay oluşturulan hesaplara uygulanacaktır.", en: "The new rule will apply only to accounts created next month." },
    { id: "PUB-046", blockId: "BLOCK-01", tr: "## önemli ## dosya adı eski, metin yamuk; doğru sürüm ek-2'de kullanılsın.", en: "## important ## the file name is old, the text is messy; use the correct version in appendix 2." },
    { id: "PUB-047", blockId: "BLOCK-01", tr: "Sandalye, olasılığı dondurup şeffaf bir cümleyi kilometreyle kokladı.", en: "The chair froze probability and smelled a transparent sentence in kilometers." },
    { id: "PUB-048", blockId: "BLOCK-01", tr: "zuu kren 55 ** alpa nör tef", en: "zuu kren 55 ** alpa nor tef" },
    { id: "PUB-049", blockId: "BLOCK-01", tr: "Değerlendirme ölçütleri veri toplanmadan önce yazılı olarak kaydedilecektir.", en: "The evaluation criteria will be recorded in writing before data collection begins." },
    { id: "PUB-050", blockId: "BLOCK-01", tr: "Kurul, başvuruları geliş sırasına göre değerlendirecek ve sonucu yazılı olarak bildirecektir.", en: "The board will evaluate applications in arrival order and notify applicants of the result in writing." },

    { id: "PUB-051", blockId: "BLOCK-02", tr: "Bakım penceresi pazar günü 01.00 ile 03.00 arasında uygulanacaktır.", en: "The maintenance window will run on Sunday from 01:00 to 03:00." },
    { id: "PUB-052", blockId: "BLOCK-02", tr: "uyarı!!! tablo eksk ama ana bulgu aynı: iki ölçüm arasında belirgin fark yok.", en: "warning!!! the table is incomplet, but the main finding is unchanged: there is no clear difference between the two measurements." },
    { id: "PUB-053", blockId: "BLOCK-02", tr: "Kayıt, bütün başvuruların kabul edildiğini belirtiyor; aynı sayfada tek bir başvurunun bile kabul edilmediği yazıyor.", en: "The record states that all applications were accepted; the same page says that not a single application was accepted." },
    { id: "PUB-054", blockId: "BLOCK-02", tr: "Bütçe, sessiz bir merdiveni içerek kararın rengini uyuttu.", en: "The budget drank a silent staircase and put the color of the decision to sleep." },
    { id: "PUB-055", blockId: "BLOCK-02", tr: "plim ursa k9 / ven dalom xx", en: "plim ursa k9 / ven dalom xx" },
    { id: "PUB-056", blockId: "BLOCK-02", tr: "revizyon-3 belki?? ana talep NET: kişisel verileri ekten kaldırın.", en: "revision-3 maybe?? main request CLEAR: remove personal data from the attachment." },
    { id: "PUB-057", blockId: "BLOCK-02", tr: "Numuneler analizden önce aynı sıcaklıkta iki saat bekletildi.", en: "The samples were kept at the same temperature for two hours before analysis." },
    { id: "PUB-058", blockId: "BLOCK-02", tr: "naro vix 000 prela ? tumi", en: "naro vix 000 prela ? tumi" },
    { id: "PUB-059", blockId: "BLOCK-02", tr: "Yönetici bu hafta hiçbir toplantı yapılmayacağını söyledi; takvim aynı hafta her gün toplantı yapılacağını kesinleştiriyor.", en: "The manager said no meetings would be held this week; the calendar confirms that meetings will be held every day of the same week." },
    { id: "PUB-060", blockId: "BLOCK-02", tr: "Şeffaf saat, yöntemin tadını ölçüp bir paragrafı kuzeye park etti.", en: "The transparent clock measured the taste of the method and parked a paragraph to the north." },
    { id: "PUB-061", blockId: "BLOCK-02", tr: "Kırmızı sonuç, kâğıdın sabrını yüzdelerle dinledi.", en: "The red result listened to the patience of the paper in percentages." },
    { id: "PUB-062", blockId: "BLOCK-02", tr: "İtirazlar, kararın bildirilmesinden sonraki yedi gün içinde yapılabilir.", en: "Appeals may be filed within seven days after the decision is announced." },
    { id: "PUB-063", blockId: "BLOCK-02", tr: "toplantı 14:00, oda belirszz, ama çevrimiçi bağlantı aynı kalıyo.", en: "meeting 14:00, room unknowwn, but the online link stays the same." },
    { id: "PUB-064", blockId: "BLOCK-02", tr: "Denekler çalışmaya gönüllü olarak katıldı; yöntem bölümünde katılımın zorunlu olduğu belirtiliyor.", en: "Participants joined the study voluntarily; the methods section states that participation was mandatory." },
    { id: "PUB-065", blockId: "BLOCK-02", tr: "felan torq 2z mav ulix ::", en: "felan torq 2z mav ulix ::" },
    { id: "PUB-066", blockId: "BLOCK-02", tr: "Dosya yalnız arşiv amacıyla tutuluyor; aynı açıklama dosyanın hiçbir koşulda saklanmadığını söylüyor.", en: "The file is retained only for archival purposes; the same statement says the file is never stored under any condition." },
    { id: "PUB-067", blockId: "BLOCK-02", tr: "SON SÜRÜM?? evet: fiyat değişmedi, sadece para birimi etiketi düzeltldi.", en: "FINAL VERSION?? yes: the price did not change, only the currency label was fixd." },
    { id: "PUB-068", blockId: "BLOCK-02", tr: "Protokolün gölgesi, metal bir nedeni beş litre boyunca düşündü.", en: "The protocol's shadow thought about a metallic reason for five liters." },
    { id: "PUB-069", blockId: "BLOCK-02", tr: "Sistem, başarısız girişlerden sonra hesabı on dakika kilitler.", en: "The system locks the account for ten minutes after failed login attempts." },
    { id: "PUB-070", blockId: "BLOCK-02", tr: "kraz minu 77 talp öre vuu", en: "kraz minu 77 talp ore vuu" },
    { id: "PUB-071", blockId: "BLOCK-02", tr: "qiv qiv 31 // norpa zel?", en: "qiv qiv 31 // norpa zel?" },
    { id: "PUB-072", blockId: "BLOCK-02", tr: "Sonuçlar bütün grupların eşit olduğunu gösteriyor; hemen ardından bir grubun diğerlerinden iki kat büyük olduğu belirtiliyor.", en: "The results show that all groups are equal; immediately afterward, one group is said to be twice as large as the others." },
    { id: "PUB-073", blockId: "BLOCK-02", tr: "Her değişiklik, uygulanmadan önce bağımsız bir gözden geçirmeden geçecektir.", en: "Every change will undergo an independent review before implementation." },
    { id: "PUB-074", blockId: "BLOCK-02", tr: "log bozuk ::::: yine de hata kodu 403 ve çözüm erişim iznini yenilemek.", en: "log corrupted ::::: still, the error code is 403 and the fix is to renew the access permission." },
    { id: "PUB-075", blockId: "BLOCK-02", tr: "Cümle, odanın sıcaklığını imzalayıp sessizliği bir takvime çevirdi.", en: "The sentence signed the room's temperature and turned silence into a calendar." },
    { id: "PUB-076", blockId: "BLOCK-02", tr: "Rapor yalnız doğrulanmış ölçümlere dayanacaktır.", en: "The report will rely only on verified measurements." },
    { id: "PUB-077", blockId: "BLOCK-02", tr: "Yeşil soru, dosyanın kokusunu üç saniyelik bir duvara bağladı.", en: "The green question tied the smell of the file to a three-second wall." },
    { id: "PUB-078", blockId: "BLOCK-02", tr: "drek pola @@ 6 6 vistan", en: "drek pola @@ 6 6 vistan" },
    { id: "PUB-079", blockId: "BLOCK-02", tr: "not: isimler silindi / satırlar kaymış / fakat öneri aynı → testi yeniden çalıştır.", en: "note: names removed / rows shifted / but the recommendation is the same → rerun the test." },
    { id: "PUB-080", blockId: "BLOCK-02", tr: "Bu anahtar veriye erişim sağlamaz; bir sonraki cümle aynı anahtarın tüm verilere tam erişim verdiğini bildiriyor.", en: "This key provides no access to the data; the next sentence reports that the same key grants full access to all data." },
    { id: "PUB-081", blockId: "BLOCK-02", tr: "acil degil... ama yarına kadar gerekli :) ana görev sözleşmeyi imzalamak.", en: "not urgnt... but needed by tomorrow :) the main task is to sign the contract." },
    { id: "PUB-082", blockId: "BLOCK-02", tr: "uln 4x premo dal seki zz", en: "uln 4x premo dal seki zz" },
    { id: "PUB-083", blockId: "BLOCK-02", tr: "Toplantıya yalnız kurul üyeleri katılabilir; tutanak aynı toplantının halka tamamen açık olduğunu belirtiyor.", en: "Only board members may attend the meeting; the minutes state that the same meeting is fully open to the public." },
    { id: "PUB-084", blockId: "BLOCK-02", tr: "Ödeme, fatura doğrulandıktan sonra beş iş günü içinde yapılır.", en: "Payment is made within five business days after the invoice is verified." },
    { id: "PUB-085", blockId: "BLOCK-02", tr: "Klavye, kararın serinliğini okuyup mantığı turuncu bir saatte sakladı.", en: "The keyboard read the coolness of the decision and stored logic in an orange hour." },
    { id: "PUB-086", blockId: "BLOCK-02", tr: "Dün, bir kilogramlık gerekçe gülümsedi ve denetimi buluta katladı.", en: "Yesterday, a one-kilogram justification smiled and folded the audit into the cloud." },
    { id: "PUB-087", blockId: "BLOCK-02", tr: "Algoritma aynı girdi için daima aynı sonucu verir; açıklama bölümünde sonucun her çalıştırmada rastgele değiştiği yazıyor.", en: "The algorithm always returns the same result for the same input; the explanation says the result changes randomly on every run." },
    { id: "PUB-088", blockId: "BLOCK-02", tr: "başlık eski!!! içerik doğru: yalnızca yönetici hesaplarında iki aşamalı doğrulama zorunlu.", en: "heading outdated!!! content correct: two-factor authentication is required only for administrator accounts." },
    { id: "PUB-089", blockId: "BLOCK-02", tr: "pum serek 90 / alta niv", en: "pum serek 90 / alta niv" },
    { id: "PUB-090", blockId: "BLOCK-02", tr: "İki değerlendirici uyuşmazsa üçüncü bir değerlendirici nihai kararı verir.", en: "If two reviewers disagree, a third reviewer makes the final decision." },
    { id: "PUB-091", blockId: "BLOCK-02", tr: "Örnekler, seçim ölçütleri açıklanmadan analize dâhil edilmeyecektir.", en: "Samples will not be included in the analysis until the selection criteria are explained." },
    { id: "PUB-092", blockId: "BLOCK-02", tr: "Sessiz politika, perşembeyi kare bir kokuyla denetledi.", en: "The silent policy audited Thursday with a square smell." },
    { id: "PUB-093", blockId: "BLOCK-02", tr: "Belge nihai ve değiştirilemez olarak işaretlenmiş; aynı kayıtta belgenin henüz oluşturulmadığı belirtilmiş.", en: "The document is marked final and immutable; the same record states that the document has not yet been created." },
    { id: "PUB-094", blockId: "BLOCK-02", tr: "nexi vor 3? tula pex pex", en: "nexi vor 3? tula pex pex" },
    { id: "PUB-095", blockId: "BLOCK-02", tr: "metin kopyalanmş, bazı harfler yok; ana mesaj: işlem geri alınabilir.", en: "text was copid, some letters are missing; main message: the operation is reversible." },
    { id: "PUB-096", blockId: "BLOCK-02", tr: "Kamera kayıt yapmadı; aynı zaman aralığı için kameranın kesintisiz görüntü kaydettiği doğrulanıyor.", en: "The camera made no recording; it is confirmed that the camera recorded continuous video during the same period." },
    { id: "PUB-097", blockId: "BLOCK-02", tr: "Eğitim materyalleri ders başlamadan bir hafta önce paylaşılacaktır.", en: "Training materials will be shared one week before the course begins." },
    { id: "PUB-098", blockId: "BLOCK-02", tr: "!!! taslak tablo / rakam 12 mi 21 mi belirsiz / kesin olan: teslimat gecikti.", en: "!!! draft table / unclear whether the number is 12 or 21 / certain point: delivery was delayed." },
    { id: "PUB-099", blockId: "BLOCK-02", tr: "Onay, mavi bir mesafeyi düşünerek dosyanın sesini dondurdu.", en: "The approval froze the sound of the file while thinking about a blue distance." },
    { id: "PUB-100", blockId: "BLOCK-02", tr: "zom rela 81 xx furu tan", en: "zom rela 81 xx furu tan" },

    { id: "PUB-101", blockId: "BLOCK-03", tr: "Kılavuz tüm parolaların en az on iki karakter olmasını şart koşuyor; aynı kılavuz sekiz karakterli her parolayı koşulsuz kabul ediyor.", en: "The guide requires every password to contain at least twelve characters; the same guide unconditionally accepts every eight-character password." },
    { id: "PUB-102", blockId: "BLOCK-03", tr: "Başvuru formunda yalnız proje amacı ve beklenen çıktı açıklanmalıdır.", en: "Only the project purpose and expected outcome should be explained in the application form." },
    { id: "PUB-103", blockId: "BLOCK-03", tr: "fren ulta 4m // qesi nop", en: "fren ulta 4m // qesi nop" },
    { id: "PUB-104", blockId: "BLOCK-03", tr: "dosya adı yanlş, sürüm etiketi yok; ama karar açık: eski kayıtlar silinmeyecek.", en: "file name wrng, version tag missing; but the decision is clear: old records will not be deleted." },
    { id: "PUB-105", blockId: "BLOCK-03", tr: "Kare rapor, sorunun gölgesini bir fincan süreyle boyadı.", en: "The square report painted the shadow of the problem for one cup of time." },
    { id: "PUB-106", blockId: "BLOCK-03", tr: "Toplantının sıcaklığı, şeffaf bir nedeni merdivene tercüme etti.", en: "The temperature of the meeting translated a transparent reason into a staircase." },
    { id: "PUB-107", blockId: "BLOCK-03", tr: "Yedek yalnız yerel diskte tutuluyor; sonraki açıklama aynı yedeğin hiçbir yerel diskte bulunmadığını söylüyor.", en: "The backup is stored only on the local disk; the next statement says the same backup is not present on any local disk." },
    { id: "PUB-108", blockId: "BLOCK-03", tr: "Denetim sonuçları kurul toplantısından sonra katılımcılarla paylaşılacaktır.", en: "The audit results will be shared with participants after the board meeting." },
    { id: "PUB-109", blockId: "BLOCK-03", tr: "ACİL? hayır / önemli evet / özet: erişim listesi cuma gününe kadar güncellensin.", en: "URGENT? no / important yes / summary: update the access list by Friday." },
    { id: "PUB-110", blockId: "BLOCK-03", tr: "xal pri 7 7 noro vem @@ ", en: "xal pri 7 7 noro vem @@" },
    { id: "PUB-111", blockId: "BLOCK-03", tr: "metnn yarısı eksik... kalanından anlaşılan: kurul ikinci seçeneği seçti.", en: "half the txt is missing... what remains shows that the board chose the second option." },
    { id: "PUB-112", blockId: "BLOCK-03", tr: "Metal salı, kararın kokusunu kare bir sessizlikte yüzdürdü.", en: "Metal Tuesday floated the smell of the decision in a square silence." },
    { id: "PUB-113", blockId: "BLOCK-03", tr: "vori tem 0q zala -- pim", en: "vori tem 0q zala -- pim" },
    { id: "PUB-114", blockId: "BLOCK-03", tr: "Katılımcı verileri analiz sonunda silinecek; aynı politika bu verilerin sonsuza kadar tutulacağını belirtiyor.", en: "Participant data will be deleted after analysis; the same policy states that these data will be retained forever." },
    { id: "PUB-115", blockId: "BLOCK-03", tr: "Yeni sensörler eski sensörlerle aynı koşullarda karşılaştırılacaktır.", en: "The new sensors will be compared with the old sensors under the same conditions." },
    { id: "PUB-116", blockId: "BLOCK-03", tr: "Yayımdan önce bütün sayısal tablolar kaynak kayıtlarla karşılaştırılmalıdır.", en: "Before publication, all numerical tables must be compared with the source records." },
    { id: "PUB-117", blockId: "BLOCK-03", tr: "juma nex 55? pol ari kex", en: "juma nex 55? pol ari kex" },
    { id: "PUB-118", blockId: "BLOCK-03", tr: "Bu sürüm hiçbir hata içermiyor; hata listesi aynı sürümde doğrulanmış on iki hata gösteriyor.", en: "This release contains no errors; the issue list shows twelve confirmed errors in the same release." },
    { id: "PUB-119", blockId: "BLOCK-03", tr: "Sarı yöntem, bir kilogramlık zamanı raporun kulağına yazdı.", en: "The yellow method wrote one kilogram of time into the report's ear." },
    { id: "PUB-120", blockId: "BLOCK-03", tr: "!!! notlar tekrar etmiş / sonuç değişmiyo: başvuru ek belge olmadan işleme alınmayacak.", en: "!!! notes repeated / result unchanged: the application will not be processed without the attachment." },
    { id: "PUB-121", blockId: "BLOCK-03", tr: "Paragraf, kuzeyin tadını ölçerek bütçeyi mor bir dakikaya çevirdi.", en: "The paragraph measured the taste of north and turned the budget into a purple minute." },
    { id: "PUB-122", blockId: "BLOCK-03", tr: "kısa özt: süre uzatıldıı, diğer şartlar aynı. tarih üstte yanlış yazılmış.", en: "short summry: deadline extendded, other conditions unchanged. the date above is wrong." },
    { id: "PUB-123", blockId: "BLOCK-03", tr: "Proje bütçesi hiç kullanılmadı; mali rapor aynı bütçenin tamamının harcandığını gösteriyor.", en: "None of the project budget was used; the financial report shows that the entire same budget was spent." },
    { id: "PUB-124", blockId: "BLOCK-03", tr: "Kullanıcı, gönderim tamamlanmadan önce taslağını silebilir.", en: "The user can delete the draft before submission is complete." },
    { id: "PUB-125", blockId: "BLOCK-03", tr: "tor 9x vela nuu pram?", en: "tor 9x vela nuu pram?" },
    { id: "PUB-126", blockId: "BLOCK-03", tr: "kemu zil 22 :: fer noma", en: "kemu zil 22 :: fer noma" },
    { id: "PUB-127", blockId: "BLOCK-03", tr: "Test sonuçları, kullanılan yazılım sürümüyle birlikte raporlanacaktır.", en: "Test results will be reported together with the software version used." },
    { id: "PUB-128", blockId: "BLOCK-03", tr: "Sessiz ölçüm, dosyanın sıcaklığını üçgen bir nedene bağladı.", en: "The silent measurement tied the temperature of the file to a triangular reason." },
    { id: "PUB-129", blockId: "BLOCK-03", tr: "Erişim yalnız mesai saatlerinde mümkündür; aynı düzenleme erişimin günün yirmi dört saati kesintisiz açık olduğunu söyler.", en: "Access is available only during working hours; the same rule says access is continuously open twenty-four hours a day." },
    { id: "PUB-130", blockId: "BLOCK-03", tr: "KOPYA KOPYA / satır sırası bozuk / net talep: üçüncü bölümü yeniden yazın.", en: "COPY COPY / line order broken / clear request: rewrite the third section." },
    { id: "PUB-131", blockId: "BLOCK-03", tr: "Kayıtlar anonimleştirildiği için kimlik belirlenemez; sonraki cümle her kişinin doğrudan adıyla tanımlandığını belirtiyor.", en: "Identities cannot be determined because the records were anonymized; the next sentence states that every person is identified directly by name." },
    { id: "PUB-132", blockId: "BLOCK-03", tr: "suv mek 18 pira xxo dal", en: "suv mek 18 pira xxo dal" },
    { id: "PUB-133", blockId: "BLOCK-03", tr: "log #44 yarım / ana hata belli: zaman damgası bir saat geri.", en: "log #44 partial / main error is clear: the timestamp is one hour behind." },
    { id: "PUB-134", blockId: "BLOCK-03", tr: "Beyaz sonuç, yöntemin ağırlığını dinleyip salı gününü dosyaladı.", en: "The white result listened to the weight of the method and filed Tuesday." },
    { id: "PUB-135", blockId: "BLOCK-03", tr: "Veriler, yalnız önceden tanımlanmış ölçütlere göre dışlanabilir.", en: "Data may be excluded only according to predefined criteria." },
    { id: "PUB-136", blockId: "BLOCK-03", tr: "BİLGİ: ek açılmıyo :( fakat mesajdaki talep açık — yeni sözleşmeyi cuma gönderin.", en: "INFO: attachment won't opn :( but the request in the message is clear — send the new contract on Friday." },
    { id: "PUB-137", blockId: "BLOCK-03", tr: "Bütün kayıtlar benzersizdir; kontrol tablosu aynı kimliğe sahip çok sayıda yinelenen kayıt gösteriyor.", en: "All records are unique; the control table shows many duplicate records with the same identifier." },
    { id: "PUB-138", blockId: "BLOCK-03", tr: "pax luro 3b nemet -- vix", en: "pax luro 3b nemet -- vix" },
    { id: "PUB-139", blockId: "BLOCK-03", tr: "Nihai karar gerekçesiyle birlikte kamuya açık biçimde yayımlanacaktır.", en: "The final decision will be published publicly together with its reasoning." },
    { id: "PUB-140", blockId: "BLOCK-03", tr: "Dosya, şeffaf bir kokuyu yarınla çarpıp sessizliği imzaladı.", en: "The file multiplied a transparent smell by tomorrow and signed the silence." },
    { id: "PUB-141", blockId: "BLOCK-03", tr: "Karşılaştırmada aynı ölçüm birimi ve aynı yuvarlama kuralı kullanılacaktır.", en: "The same unit of measurement and rounding rule will be used in the comparison." },
    { id: "PUB-142", blockId: "BLOCK-03", tr: "Rapor bugün onaylandı; aynı raporun onay sürecinin gelecek hafta ilk kez başlayacağı yazıyor.", en: "The report was approved today; it also says that its approval process will begin for the first time next week." },
    { id: "PUB-143", blockId: "BLOCK-03", tr: "Soğuk gerekçe, turuncu bir kilometreyi toplantının cebine koydu.", en: "The cold justification put an orange kilometer into the meeting's pocket." },
    { id: "PUB-144", blockId: "BLOCK-03", tr: "rakamlar kaymş / başlık iki kez / sonuç: toplam maliyet tahmini aşmadı.", en: "numbers shiftedd / heading twice / result: total cost did not exceed the estimate." },
    { id: "PUB-145", blockId: "BLOCK-03", tr: "gora minu 88? tel pox", en: "gora minu 88? tel pox" },
    { id: "PUB-146", blockId: "BLOCK-03", tr: "zir voma 1k lal tren", en: "zir voma 1k lal tren" },
    { id: "PUB-147", blockId: "BLOCK-03", tr: "taslk / tarih yok / yine de sorumlu kişi ve görev net: Ayşe değil, 'ekip lideri' raporu kontrol edecek.", en: "drft / no date / still, the role and task are clear: not a named person, the 'team lead' will review the report." },
    { id: "PUB-148", blockId: "BLOCK-03", tr: "Her katılımcıya aynı yönerge ve aynı süre verilecektir.", en: "Every participant will receive the same instruction and the same amount of time." },
    { id: "PUB-149", blockId: "BLOCK-03", tr: "Dakikanın rengi, bütçenin sesini yuvarlak bir pencereye taşıdı.", en: "The color of the minute carried the sound of the budget to a round window." },
    { id: "PUB-150", blockId: "BLOCK-03", tr: "İşlem geri döndürülemez olarak tanımlanıyor; aynı adımın tek tıklamayla tamamen geri alınabildiği belirtiliyor.", en: "The operation is described as irreversible; the same step is said to be fully reversible with one click." }
  ])
});
